version: '3.8'

services:
  db:
    image: postgres:15
    container_name: ai_writing_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ai_writing_platform
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - ai_writing_network

  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: ai_writing_app
    restart: always
    ports:
      - '5000:5000'
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/ai_writing_platform?schema=public
      - NODE_ENV=development
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - db
    networks:
      - ai_writing_network

networks:
  ai_writing_network:
    driver: bridge

volumes:
  postgres_data: